<?php  
	$session_lang = new Zend_Session_Namespace('lang');
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<?php $session = new Zend_Session_Namespace('auth'); ?>
<?php $add_url = $this->url(array('module'=>'customer','controller'=>'index','action'=>'add'),null,true);?>
<?php $edit_url = $this->url(array('module'=>'customer','controller'=>'index','action'=>'edit'),null,true);?>  
<?php $delete_url = $this->url(array('module'=>'customer','controller'=>'index','action'=>'delete'),null,true);?> 
<style>
thead tr th{font-size: 13px; text-align: center !important;}
td{font-size: 12px; text-align: center !important;}
button{ margin-right: 5px;} td{ font-size:12px;} 
.breadCrumb{ margin-top:5px;}
</style> 
<form class="form-horizontal" id="popup-validation" enctype="multipart/form-data" method="post">
    <div class=" clearfix">    
             
    </div>
    <div class="content">                                  
            <div class="widget">
                <div class="head">                    
                    <div class="btn-group pull-left">
                    	<h2><span class="icon-th"></span><?php echo $tr->translate('TABLE'); ?></h2>   
                    </div>
                    <div class="panel panel-default">
                    	<div class="panel-heading">
                    		<div  class="btn-group pull-right" style="margin-top:2px;">				
									<a href="<?php echo $add_url;?>">
									<button type="button" class="btn btn-primary "><span class="icon-plus-sign icon-white" ></span> <?php echo $tr->translate('NEW'); ?> </button>					
									</a>
									<button type="submit" name="update" class="btn btn-primary"><i class="icon-edit icon-white"> </i> <?php echo $tr->translate('UPDATE'); ?> </button>
									<button type="submit" name="delete" class="btn btn-danger"><i class="icon-remove icon-white"> </i> <?php echo $tr->translate('DELETE'); ?> </button>
							</div>	             	     	                                         
                         </div>                    
                	</div>
                <div style="clear:both"></div>
                <div class="panel-body">                
                    <div class="block-fluid">
                        <table class="fpTable datatable" cellpadding="0" cellspacing="0" width="100%" id="customers2">
                            <thead>
                            	<tr>
									<th width="5%"><?php if($session_lang->lang_id==2){ echo $tr->translate('NUM'); } else{ ?>N <sup> <u>o</u></sup><?php }?></th>
		                        	<th width="10%"><?php echo $tr->translate('CHECK_BOX'); ?></th>
		                            <th><?php echo $tr->translate('NAME_EN'); ?></th>
		                            <th><?php echo $tr->translate('NAME_KM'); ?></th>
		                            <th><?php echo $tr->translate('ICON'); ?></th>
		                        	<th width="10%" class="TAC"><?php echo $tr->translate('ACTION'); ?></th>
		                       </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1;?>
                    		<?php foreach($this->getdata as $data){?>
		                    	<tr class="odd gradeX">
		                    		<td><?php echo $i++;?></td>
		                        	<td><span class=""><input class="uniform" name="checkBox" value="<?php echo $data['customer_id'];?>" type="checkbox"></span></td>
		                        	<td><a href="<?php echo $edit_url?>/id/<?php echo $data['customer_id'];?>"><?php echo $data['name_en'];?></a></td>
		                        	<td><a href="<?php echo $edit_url?>/id/<?php echo $data['customer_id'];?>"><?php echo $data['name_kh'];?></a></td>
		                       		<td><img src="<?php echo $this->baseUrl()?>/icon/<?php echo $data['icon'];?>" style="width: 50px;"/></td>
                        			<td>
                                    	<?php if($data['status']== 1){?>                        
                        				<button style="background:none; margin:0; padding:0;border:none;" type="submit" name="status" value="<?php echo $data['customer_id'];?>" >
                                        	<span class="icon-ok"></span>
                                         </button>
		                        		<?php }else {?>
                                        <button style="background:none; margin:0; padding:0;border:none;" type="submit" name="unstatus" value="<?php echo $data['customer_id'];?>" >
		                        			<span class="icon-off"></span>
                                        </button>
		                        		<?php }?>
                                        <a href="<?php echo $edit_url?>/id/<?php echo $data['customer_id'];?>"><span class="icon-pencil"></span></a> 
                                        <a href="<?php echo $delete_url?>/id/<?php echo $data['customer_id'];?>"><span class="icon-trash"></span></a>
                                    </td>
                                </tr> 
                            <?php } ?>                   
                            </tbody>
                        </table>                    
                    </div> 
           		</div>            
			</div>  
    	</div> 
    </div> 
</form>