<?php  
	$session_lang = new Zend_Session_Namespace('lang');
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frmSearch;
	//$url_barcode = $this->url(array("module"=>"loan","controller"=>"product","action"=>"generate-barcode","product_code"=>$client['product_code']),null,true);
?>
<?php $session = new Zend_Session_Namespace('auth'); ?>
<?php $add_url = $this->url(array('module'=>'product','controller'=>'index','action'=>'add'),null,true);?>
<?php $edit_url = $this->url(array('module'=>'product','controller'=>'index','action'=>'edit'),null,true);?>  
<?php $delete_url = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete'),null,true);?> 
<?php $url_barcode_view = $this->url(array('module'=>'product','controller'=>'index','action'=>'barcodeview'),null,true);?> 
<style>
dt{ display: none;}
.btn{ margin-right: 5px!important;margin-left: 5px!important;} 
.breadCrumb{ margin-top:5px;}
.ui-pnotify,custom{display: none !important;}
</style>
<style>
thead tr th{font-size: 13px; text-align: center !important;}
td{font-size: 12px; text-align: center !important;}
button{ margin-right: 5px;} td{ font-size:12px;} 
.breadCrumb{ margin-top:5px;}
</style> 
<form action="<?php echo $this->baseUrl();?>/product/index" class="form-horizontal" id="popup-validation" enctype="multipart/form-data" method="post">
    <div class=" clearfix">    
             
    </div>
    <div class="content">                                  
            <div class="widget">
                <div class="head">                    
                    <div class="btn-group pull-left">
                    	<h2><span class="icon-th"></span><?php echo $tr->translate('TABLE'); ?></h2>   
                    </div>
					<div class="panel panel-default">
                    	<div class="panel-heading">
                   			<div  class="btn-group pull-right" style="margin-top:2px;">	
                            	<button class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-print"></i> Export & Print  <span class="caret"> </span></button>
                                <ul class="dropdown-menu">                                   
                                 	<li class="divider"></li>
                               		<li><a href="#" onClick ="$('#customers2').tableExport({type:'excel',escape:'false'});"><img src='<?php echo $this->baseUrl();?>/img/icons/xls.png' width="24"/> Excel </a></li>
                                  	<li><a href="#" onClick ="$('#customers2').tableExport({type:'doc',escape:'false'});"><img src='<?php echo $this->baseUrl();?>/img/icons/word.png' width="24"/> Word </a></li>
	                              	<li><a href="#" onClick ="Clickheretoprint()"><img src='<?php echo $this->baseUrl();?>/img/icons/print.png' width="24"/> Print </a></li>
                            	</ul>
                            </div>   		    	     	                                         
                         </div>                    
                	</div>
                    <div class="panel panel-default">
                    	<div class="panel-heading">
                    		<div  class="btn-group pull-right" style="margin-top:2px;">				
									<a href="<?php echo $add_url;?>">
									<button type="button" class="btn btn-primary "><span class="icon-plus-sign icon-white" ></span> <?php echo $tr->translate('NEW'); ?> </button>					
									</a>
									<button type="submit" name="update" class="btn btn-primary"><i class="icon-edit icon-white"> </i> <?php echo $tr->translate('UPDATE'); ?> </button>
									<button type="submit" name="delete" class="btn btn-danger"><i class="icon-remove icon-white"> </i> <?php echo $tr->translate('DELETE'); ?> </button>
							</div>	             	     	                                         
                         </div>                    
                	</div>
                <div style="clear:both"></div>
                <div class="panel-body"> 
					<div class="block-fluid">
                    	<div class="row-form">
                    		<div class="span1"><?php echo $tr->translate('SEARCH') ?>:</div>
			                 <div class="span2"><?php echo $frm->getElement('txt_search');?></div> 							 
			                 <div class="span3">
			                 	<select id="add_item" name="add_item" onChange="getItemOrder();" class="select" style="width:100%" tabindex="4">
									<?php echo $this->itemsOption; ?>
								</select>
			                 </div>
			                 <div class="span3">
			                 	<?php echo $frm->getElement('cat_id');?>
			                 </div>
			                 <div class="span3">
			                 	<?php echo $frm->getElement('brand');?>
			                 </div>
			                 <div class="span1">
			                 	<button type="submit" name="search" class="btn btn-primary"><i style="font-size:15px;" class="icon-search icon-white"> </i></button>
			                 </div>
	                    </div>
					</div>
					 <div style="clear:both"></div>
                    <div class="block-fluid">
                        <table class="fpTable datatable" cellpadding="0" cellspacing="0" width="100%" id="customers2">
                            <thead>
                            	<tr>
									<th width="5%"><?php if($session_lang->lang_id==2){ echo $tr->translate('NUM'); } else{ ?>N <sup> <u>o</u></sup><?php }?></th>
		                        	<th width="10%"><?php echo $tr->translate('CHECK_BOX'); ?></th>
		                        	 <th><?php echo $tr->translate('P_CODE'); ?></th>
		                            <th><?php echo $tr->translate('NAME_EN'); ?></th>
		                            <th><?php echo $tr->translate('NAME_KM'); ?></th>
		                             <th><?php echo $tr->translate('PRICE'); ?></th>
		                             <th><?php echo $tr->translate('CATEGORY'); ?></th>
		                            <th><?php echo $tr->translate('ICON'); ?></th>
		                            <th><?php echo $tr->translate('BARCODE');?></th>
		                        	<th width="10%" class="TAC"><?php echo $tr->translate('ACTION'); ?></th>
		                       </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1;?>
                    		<?php 
							//print_r($this->getdata);
                    			foreach($this->getdata as $data){ 
                    			$url_barcode = $this->url(array("module"=>"product","controller"=>"index","action"=>"generate-barcode","product_code"=>$data['item_code']),null,true);
                    		?>
		                    	<tr class="odd gradeX">
		                    		<td width="3%"><?php echo $i++;?></td>
		                        	<td width="5%"><span class=""><input class="uniform" name="checkBox" value="<?php echo $data['pro_id'];?>" type="checkbox"></span></td>
		                        	<td><a href="<?php echo $edit_url?>/id/<?php echo $data['pro_id'];?>"><?php echo $data['item_code'];?></a></td>
		                        	<td><a href="<?php echo $edit_url?>/id/<?php echo $data['pro_id'];?>"><?php echo $data['name_en']." - ". $data['item_size'];?></a></td>
		                        	<td><a href="<?php echo $edit_url?>/id/<?php echo $data['pro_id'];?>"><?php echo $data['name_kh'];?></a></td>
		                       		<td><?php echo $data['price_per_qty']." ".$data['icons'];?></td>
		                       		<td><?php echo $data['cat_name'];?></td>
		                       		<td><img src="<?php echo $this->baseUrl()."/icon/".$data['icon'];?>" style="width: 50px;"/></td>
		                       		<td><a href="<?php echo $url_barcode_view;?>/id/<?php echo $data['pro_id'];?>"  target="_new"><img src="<?php echo $url_barcode;?>" /></a></td>
                        			<td width="5%">
                                    	
                                        <a href="<?php echo $edit_url?>/id/<?php echo $data['pro_id'];?>"><span class="icon-pencil"></span></a> 
                                        <a href="<?php echo $delete_url?>/id/<?php echo $data['pro_id'];?>"><span class="icon-trash"></span></a>
                                    </td>
                                </tr> 
                            <?php } ?>                   
                            </tbody>
                        </table>  

							<div  id="printShow" style="display: none;">
								
							<table style="width: 100%; border: 1px solid #DDD;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
                            <thead>
                            	<tr style="font-size: 9px; text-align:center; background-color: #F2EDED !important;">
									<th width="5%" style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;padding: 5px;"><?php if($session_lang->lang_id==2){ echo $tr->translate('NUM'); } else{ ?>N<sup><u>o</u></sup><?php }?></th>
		                            <th style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;padding: 5px;"><?php echo $tr->translate('PRODUCT'); ?></th>
		                            <th style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;padding: 5px;"><?php echo $tr->translate('ITEM_NAME'); ?></th>
		                            <th style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;padding: 5px;"><?php echo $tr->translate('PRICE'); ?></th>
		                            <th style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;padding: 5px;"><?php echo $tr->translate('BARCODE'); ?></th>
		                       </tr>
                            </thead>
                            <tbody>
                            <?php $i = 1;?>
                    		<?php foreach($this->getdata as $rs){
									$url_barcode = $this->url(array("module"=>"product","controller"=>"index","action"=>"generate-barcode","product_code"=>$rs['item_code']),null,true);
								?>
		                    	<tr class="odd gradeX" style="font-size: 9px;text-align:center;">
		                    		<td style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;"><?php echo $i++;?></td>
		                        	<td style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;"><?php echo $rs['item_code'];?></td>
		                        	<td style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;"><?php echo $rs['name_kh']."(".$rs["item_size"].")<br />".$rs['name_en']."(".$rs["item_size"].")";?></td>
		                        	<td style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;"><?php echo $rs['price_per_qty'];?></td>
		                        	<td style="border-right: 1px solid #DDD;border-bottom: 1px solid #DDD;"><img src="<?php echo $url_barcode?>" /></td>
                                </tr> 
                            <?php } ?>
								
                            </tbody>
                        </table> 
                        </div> 
                    </div> 
           		</div>            
			</div>  
    	</div> 
    </div> 
</form>
<script>
function Clickheretoprint()
{ 
  var disp_setting="toolbar=yes,location=no,directories=yes,menubar=yes,"; 
      disp_setting+="scrollbars=yes,width=800, height=500, left=100, top=25"; 
  var content_vlue = document.getElementById("printShow").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head><title>Western University</title>'); 
   docprint.document.write('</head><body onLoad="self.print()" style=" margin:0px; font-family:Verdana; font-size:8px;"><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></body></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
</script>