<!DOCTYPE html>
<html lang="en">
<head>        
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
    
    <!--[if gt IE 8]>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <![endif]-->        
    
    <link href="<?php echo $this->baseUrl()?>/css/stylesheets.css" rel="stylesheet" type="text/css" />      
    <!--[if lt IE 10]>
        <link href="<?php echo $this->baseUrl()?>/css/ie.css" rel="stylesheet" type="text/css" />
    <![endif]-->        
    <link rel="icon" type="image/ico" href="<?php echo $this->baseUrl()?>/favicon.ico"/>
      
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jquery/jquery-1.10.2.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jquery/jquery-ui-1.10.1.custom.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jquery/jquery-migrate-1.1.1.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jquery/globalize.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/other/excanvas.js'></script>
   
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/other/jquery.mousewheel.min.js'></script>
        
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/bootstrap/bootstrap.min.js'></script>            
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/cookies/jquery.cookies.2.2.0.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/fancybox/jquery.fancybox.pack.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jflot/jquery.flot.js'></script>    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jflot/jquery.flot.stack.js'></script>    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jflot/jquery.flot.pie.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jflot/jquery.flot.resize.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/epiechart/jquery.easy-pie-chart.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/knob/jquery.knob.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/sparklines/jquery.sparkline.min.js'></script>    
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/pnotify/jquery.pnotify.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/fullcalendar/fullcalendar.min.js'></script>        
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/datatables/jquery.dataTables.min.js'></script>    
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/wookmark/jquery.wookmark.js'></script>        
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jbreadcrumb/jquery.jBreadCrumb.1.1.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/mcustomscrollbar/jquery.mCustomScrollbar.min.js'></script>
    
    <script type='text/javascript' src="<?php echo $this->baseUrl()?>/js/plugins/uniform/jquery.uniform.min.js"></script>
    <script type='text/javascript' src="<?php echo $this->baseUrl()?>/js/plugins/select/select2.min.js"></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/tagsinput/jquery.tagsinput.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/maskedinput/jquery.maskedinput-1.3.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/multiselect/jquery.multi-select.min.js'></script>    
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/validationEngine/languages/jquery.validationEngine-en.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/validationEngine/jquery.validationEngine.js'></script>        
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/stepywizard/jquery.stepy.js'></script>
        
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/animatedprogressbar/animated_progressbar.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/hoverintent/jquery.hoverIntent.minified.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/media/mediaelement-and-player.min.js'></script>    
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/cleditor/jquery.cleditor.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/shbrush/XRegExp.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/shbrush/shCore.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/shbrush/shBrushXml.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/shbrush/shBrushJScript.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/shbrush/shBrushCss.js'></script>    
        
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/filetree/jqueryFileTree.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/slidernav/slidernav-min.js'></script>    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/isotope/jquery.isotope.min.js'></script>    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jnotes/jquery-notes_1.0.8_min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/jcrop/jquery.Jcrop.min.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/ibutton/jquery.ibutton.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins/scrollup/jquery.scrollUp.min.js'></script>
    
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/plugins.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/charts.js'></script>
    <script type='text/javascript' src='<?php echo $this->baseUrl()?>/js/actions.js'></script>
    
    
</head>
<body>

    <div class="header" >
      
    </div>    
    
    <div class="login" id="login" style="margin-top: 50px;">
        <div class="wrap">
            <h1 style="text-align: center;" >Welcom. Please Log In</h1>
            <label style="color: red; text-align: center;"><?php echo $this->msg;?></label>
            <form action="" method="post" id="validate">
            <div class="row-fluid">
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-user"></i></span>
                    <input type="text" name="login" value="" placeholder="Username" class="validate[required]"/>
                </div>                                                 
                <div class="input-prepend">
                    <span class="add-on"><i class="icon-exclamation-sign"></i></span>
                    <input type="password" name="password" value="" placeholder="Password" class="validate[required]"/>
                </div>
                <div class="input-prepend">
		           <select name="lange">
		                  <option value="2"> Khmer</option>                                                                
		           </select>
                </div>            
                <div class="dr"><span></span></div>                                
                          
	            <div class="span12" style="text-align: center;">
	                <div class="span5">                    
	                    <button type="reset" class="btn btn-block btn-primary" value="Reset"><i class="icon-repeat icon-white"></i> Reset </button>              
	                </div>
	                <div class="span5 TAR">
	                    <button type="submit" class="btn btn-block btn-primary" value="Log In"><i class="icon-lock icon-white"></i> Log In </button>
	                </div>
	            </div>
            </div>  
            </form>        
        </div>
    </div>
</body>
</html>
