<?php 
	error_reporting(0);
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$product = $this->getdata;
	$order = $this->order;
	$frm = $this->frm;
	$FrmOrderUpdate =$this->FrmSaleOrderUpdate;
	$session = new Zend_Session_Namespace('auth');
	$user = $session->fullname;
	$session_lang = new Zend_Session_Namespace('lang');
	$currency_setting = $this->currency_setting;
	$company_name=$this->company_name;
	$slogan=$this->slogan ;
	$address=$this->address ;
	$tel=$this->tel ;
	$user = $this->user;
	$qty_warning = $this->qty_warning;
?>
<style>
dt{ display: none;}
.btn{ margin-right: 5px!important;margin-left: 5px!important;} 
.breadCrumb{ margin-top:5px;}
.ui-pnotify,custom{display: none !important;}
</style>
<script src="<?php echo $this->baseUrl();?>/js/atn-cart.js"></script>
<form id="order_form" enctype="multipart/form-data" method="post">
    <div class="content">      
        <div class="row-fluid">          
            <div class="span12">                
				<div class="widget">
                    <div class="head dark">
                        <div class="icon"><i class="icos-newtab"></i></div>
                        <h2><?php echo $tr->translate('ORDER_AND_INVOICE') ?></h2>
                    </div>  
                    <div class="block-fluid tabbable">                    
                        <!--<ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">
                            	<i class="icon-tags"></i> <?php echo $tr->translate('ORDER'); ?>
                            </a></li>
                            <li><a href="#tab2" data-toggle="tab"><i class="icon-list"></i> <?php echo $tr->translate('LIST_INVOICE'); ?></a></li>
                        </ul>-->
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                            	<div id="popup" class="alert alert-warning"></div>
	                            <div class="block-fluid">
								<div class="row-form">
								         <div class="span2"><?php echo $tr->translate('PRODUCT') ?>:</div>
								         <div class="span10">
								              <select id="add_item" name="add_item" onChange="getItemOrder();" class="select" style="width:100%" tabindex="1">
													<?php echo $this->itemsOption; ?>
										      </select>
								         </div>
								    </div>
	                            	<div class="row-form">
	                            		<div class="span0"><input type="hidden" name="currency_setting" id="currency_setting" value="<?php echo $currency_setting;?>" /></div>
			                            
			                            <div class="span1"><?php echo $tr->translate('CUSTOMER') ?>:</div>
			                            <div class="span3">
			                                <?php echo $frm->getElement('customer');?>
			                            </div>
			                            <div class="span1"><?php echo $tr->translate('DATE') ?>:</div>
			                            <div class="span2">
			                            	<div class="input-prepend input-append">
				                                <?php echo $frm->getElement('date');?>  
				                                <span class="add-on" style="right"><i class="icon-calendar"></i></span>                              
				                          </div>  
			                                <?php //echo $frm->getElement('dates');?>
			                            </div>
										<div class="span1"><?php echo $tr->translate('ORDER_NO') ?>:</div>
			                            <div class="span3"><?php echo $frm->getElement('saleorder_no');?></div> 
			                        </div>
			                        
			                        <div class="row-form">
			                        	<table class="datatable" cellpadding="0" cellspacing="0" width="100%" id="order_item">
				                            <thead>
				                                <tr>
				                                	<th width="3%"><?php echo $tr->translate('NUM') ?></th>
				                                    <th width="3%"><?php echo $tr->translate('DELETE') ?></th>
				                                    <th width="24%"><?php echo $tr->translate('PRODUCT') ?></th>
				                                   <!-- <th width="10%"><?php echo $tr->translate('UNIT_QTY') ?></th>-->
				                                   <!--  <th width="15%"><?php echo $tr->translate('UNIT_PRICE') ?></th>-->
				                                    <th width="10%"><?php echo $tr->translate('QTY_PER_UNIT') ?></th>
				                                    <th width="15%"><?php echo $tr->translate('PRICE_PER_QTY') ?></th>
				                                    <th width="10%"><?php echo $tr->translate('TOTAL_PRICE') ?></th>
				                                </tr>
				                            </thead>
				                         </table>
										<input type="hidden" name="identity" id="identity">
			                        </div>
			                        <div class="row-form">
			                        	<div class="span2"><?php echo $tr->translate('CURRENCY_TYPE') ?>: <input type="hidden" id="rate" name="rate" /></div>
			                        	<div class="span4"><?php echo $frm->getElement('currency');?></div>
								         <div class="span2"><?php echo $tr->translate('GRAND_TOTAL') ?>:</div>
								         <div class="span4">
											<div class="input-append">
												<input type="text" name="gran_total" id="gran_total" value="0"/>
												<span class="add-on">
												<label id="cu_icon_gran_total"></label>
												</span>
											</div>
										</div>
								    </div>
									<div class="row-form">
			                        	<div class="span6"></div>
								         <div class="span2"><?php echo $tr->translate('PAYMENT_AMOUNT') ?>:</div>
								         <div class="span4">
											<div class="input-append">
												<input type="text" name="gran_pay" id="gran_pay" value="0" onChange="doBalance();"/>
												<span class="add-on">
													<label id="cu_icon_gran_pay"></label>
												</span>
											</div>
										</div>
								    </div>
									<div class="row-form">
			                        	<div class="span6"></div>
								         <div class="span2"><?php echo $tr->translate('BALANCE') ?>:</div>
								         <div class="span4">
											<div class="input-append">
												<input type="text" name="balance" id="balance" value="0"/>
												<span class="add-on">
													<label id="cu_icon_balance"></label>
												</span>
											</div>
										</div>
								    </div>
			                        <div class="row-form">
			                        
			                            <div class="span6" style="float: right;">
			                            	<button id="save" type="button" class="btn btn-primary btn-sm btn-grad" onclick="submitData();" name="save"><i class="icon-share icon-white"></i> Save</button>
			                            	<button id="saveprint" type="button" class="btn btn-success" Onclick="Clickheretoprint();"><i class="icon-print icon-white"></i> Save & Print</button>
			                            	
			                            	
			                            </div>
			                        </div>
			                    </div> 
			                    <!-- Print Blog  -->
			                    
			                    <div class="row-fluid" style="display: block">
			                    	<div  id="printShow" style="display: none;">
			                    		<div class="row-form" style="width:100%; padding-top:5px;">
			                    			<table class="datatable" cellpadding="0" cellspacing="0" width="100%" style="width: 100%; border:0 0 0px 0 solid #DDD;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
												<tr>
													<td style="width:30%"> <img src="<?php echo $this->baseUrl();?>/img/rice.png"  width="50px" /> <img src="<?php echo $this->baseUrl();?>/img/pilow.png" style="padding-top:10px;"  width="50px" />  </td>
													<td style="text-align:center; width:40%; color:#36F; font-family:'Khmer OS Muol Light';font-size:10px;">
														<?php
													 		$arrays = explode(",", $company_name);
															$count = count($arrays);
															for ($i=0;$i<$count;$i++){
																echo $arrays[$i]."<br />";
															}
														?>
													</td>
													<td style="width:30%">  <img style="float:right" src="<?php echo $this->baseUrl();?>/img/fan.png" width="70px" /> <img style="padding-top:10px;" src="<?php echo $this->baseUrl();?>/img/baket.png"  width="70px" /> </td>
												</tr>
												<tr>
													<td style="width:30%; font-size:8px;font-family:'Khmer OS Muol Light'"><?php echo $address;?></td>
													<td style="width:40%;text-align:center;font-size:8px;font-family:'Khmer OS Muol Light'"><?php echo $slogan; ?><td>
													<td><?php //echo $slogan;?></td>
												</tr>
												<tr>
													<td style="width:30%; color:#36F; font-size:8px;">
                                                        <span>
														<?php
													 		$arrays = explode(",", $tel);
															$count = count($arrays);
															$is_set = 0;
															
															for ($i=0;$i<$count;$i++){
																if($is_set!=1){
																	$tel_s = "Tel :";
																}else{
																	$tel_s = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
																}
																echo  $tel_s.$arrays[$i]."<br />";
																$is_set=1;
															}
														?>
                                                        </span>
													</td>
													<td style="width:40%; font-size:8px; font-family:'Khmer OS Muol Light'​​​" align="center"><span><?php echo $tr->translate('INVOICE') ?><br /> INVOICE </span></td>
													<td style="width:30%; text-align:right; font-size:8px;">
													<?php echo $tr->translate('CUSTOMER') ?>:
													 <label id="lb_customer"></label><br />
													<?php echo $tr->translate('ORDER_NO') ?>:
                                                    <label id="lb_order_no" style="font-family:'Khmer OS Muol Light'; font-size:10px;color:#F00;"></label><br />
                                                    <?php echo $tr->translate('DATE') ?>:
                                                    <label id="lb_date"></label>
                                                    </td>
												</tr>
											</table>
			                    		</div>
			                    		<div style="height: 1px; clear:both;" ></div>
			                    		<div id="item_print">
				                        	<table class="datatable" width="100%" id="order_item_print" style=" border-collapse: collapse;">
				                            <thead>
				                                <tr style="font-size: 8px; border-collapse: collapse;">
				                                	<th width="2%" style="background-color: #D6D5D5;border: 1px solid #272222; border-collapse: collapse;"><?php echo $tr->translate('NUM') ?></th>
				                                    <th width="43%" style="background-color: #D6D5D5;border: 1px solid #272222; border-collapse: collapse;padding-left:5px;line-height:30px"><?php echo $tr->translate('PRODUCT') ?></th>
				                                   <!-- <th width="10%" style="border: 1px solid #272222; border-collapse: collapse;"><?php //echo $tr->translate('UNIT_QTY') ?></th>-->
				                                    <!-- <th width="15%" style="border: 1px solid #272222; border-collapse: collapse;"><?php //echo $tr->translate('UNIT_PRICE') ?></th>-->
				                                    <th width="7%" style="background-color: #D6D5D5;border: 1px solid #272222; border-collapse: collapse;"><?php echo $tr->translate('QTY_PER_UNIT') ?></th>
				                                    <th width="10%" style="background-color: #D6D5D5;border: 1px solid #272222; border-collapse: collapse;"><?php echo $tr->translate('PRICE_PER_QTY') ?></th>
				                                    <th width="10%" style="background-color: #D6D5D5;border: 1px solid #272222; border-collapse: collapse;"><?php echo $tr->translate('TOTAL_PRICE') ?></th>
				                                </tr>
				                            </thead>
				                         </table>
			                    		</div>
										<div style="height: 1px; clear:both;" ></div>
										<div class="row-form">
											<table cellpadding="0" cellspacing="0" width="100%" id="order_item_print" style="width: 100%; border:0 0 0px 0 solid #DDD;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
												<tr style="font-size: 8px; b">
													<td style=""><?php echo $tr->translate('CURRENCY_TYPE') ?>:</td>
													<td style=""><label id="lb_cu_type"></label></td>
													<td><?php echo $tr->translate('GRAND_TOTAL') ?>:</td>
													<td style="" align="center"><label id="lb_gran_total_print"></label><label id="lb_cu_icon_gran_total"></label></td>
												</tr>
												<tr style="font-size: 8px;">
													<td></td>
													<td></td>
													<td><?php echo $tr->translate('PAYMENT_AMOUNT') ?>:</td>
													<td style="" align="center"><label id="lb_gran_pay_print"></label><label id="lb_cu_icon_gran_pay"></label></td>
												</tr>
												<tr style="font-size: 8px;">
													<td></td>
													<td></td>
													<td><?php echo $tr->translate('BALANCE') ?>:</td>
													<td style="" align="center"><label id="lb_balance_print"></label><label id="lb_cu_icon_balance"></label></td>
												</tr>
                                                <tr>
                                                	<div style="padding-top:1px;"></div>
                                                	<td align="left" style="font-size:8px"> <p> Customer's Signature </p> <p> ហត្ថលេខាអ្នកទិញ </p> </td>
                                                    <td></td>
                                                    <td></td>
                                                    <td align="center" style="font-size:8px"><p> Seller's Signature </p> <p> ហត្ថលេខាអ្នកលក់​</p></td>
                                                </tr>
											</table>
										</div>
								    </div>
								</div>	
								<div  id="printForOwner" style="display: none; background:#D0A7B8 !important;">
			                    		<div class="row-form" style="width:100%; padding:0;" id="header1">
			                    			<table class="datatable" cellpadding="0" cellspacing="0" width="100%" style="width: 100%; border:0 0 0px 0 solid #DDD;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
												<tr>
													<td style="width:30%"> <img src="<?php echo $this->baseUrl();?>/img/rice.png"  width="50px" /> <img src="<?php echo $this->baseUrl();?>/img/pilow.png" style="padding-top:10px;"  width="50px" /> </td>
													<td style="text-align:center; width:40%; color:#36F; font-family:'Khmer OS Muol Light';font-size:8px;">
														<?php
													 		$arrays = explode(",", $company_name);
															$count = count($arrays);
															for ($i=0;$i<$count;$i++){
																echo $arrays[$i]."<br />";
															}
														?>
													</td>
													<td style="width:30%">  <img style="float:right" src="<?php echo $this->baseUrl();?>/img/fan.png" width="70px" /><img style="padding-top:10px;" src="<?php echo $this->baseUrl();?>/img/baket.png"  width="70px" /></td>
												</tr>
												<tr>
													<td style="width:30%; font-size:8px;font-family:'Khmer OS Muol Light'"><?php echo $address;?></td>
													<td style="width:40%;text-align:center;font-size:8px;font-family:'Khmer OS Muol Light'"><?php echo $slogan; ?><td>
													<td><?php //echo $slogan;?></td>
												</tr>
												<tr>
													<td style="width:30%; color:#36F; font-size:8px;">
                                                    	<span></span>
                                                        <span>
														<?php
													 		$arrays = explode(",", $tel);
															$count = count($arrays);
															$is_set = 0;
															
															for ($i=0;$i<$count;$i++){
																if($is_set!=1){
																	$tel_s = "Tel :";
																}else{
																	$tel_s = "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;";
																}
																echo  $tel_s.$arrays[$i]."<br />";
																$is_set=1;
															}
														?>
                                                        </span>
													</td>
													<td style="width:40%; font-size:10px; font-family:'Khmer OS Muol Light'​​​" align="center"><span><?php echo $tr->translate('INVOICE') ?><br /> INVOICE </span></td>
													
													<td style="width:30%; text-align:right; font-size:8px;">
														<?php echo $tr->translate('CUSTOMER') ?>:
														<label id="lb_customers"></label><br />
														<?php echo $tr->translate('ORDER_NO') ?>:
                                                    <label id="lb_order_nos" style="font-family:'Khmer OS Muol Light'; font-size:12px;color:#F00;"></label><br />
                                                    <?php echo $tr->translate('DATE') ?>:
                                                    <label id="lb_dates"></label>
                                                    </td>
												</tr>
											</table>
			                    		</div>
			                    		<div style="height: 1px; clear:both;" ></div>
			                    		<div id="item_print">
				                        	<table class="datatable" width="100%" id="order_item_owner" style=" border-collapse: collapse;">
				                            <thead>
				                                <tr style="font-size: 9px; border-collapse: collapse;">
				                                	<th width="2%" style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><?php echo $tr->translate('NUM') ?></th>
				                                    <th width="43%" style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><?php echo $tr->translate('PRODUCT') ?></th>
				                                    <th width="7%" style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><?php echo $tr->translate('QTY_PER_UNIT') ?></th>
				                                    <th width="10%" style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><?php echo $tr->translate('PRICE_PER_QTY') ?></th>
				                                    <th width="10%" style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><?php echo $tr->translate('TOTAL_PRICE') ?></th>
				                                </tr>
				                            </thead>
				                         </table>
			                    		</div>
										<div style="height: 1px; clear:both;" ></div>
										<div class="row-form">
											<table cellpadding="0" cellspacing="0" width="100%" id="order_item_print" style="width: 100%; border:0 0 0px 0 solid #DDD;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
												<tr style="font-size: 8px; b">
													<td style=""><?php echo $tr->translate('CURRENCY_TYPE') ?>:</td>
													<td style=""><label id="lb_cu_types"></label></td>
													<td><?php echo $tr->translate('GRAND_TOTAL') ?>:</td>
													<td style="" align="center"><label id="lb_gran_total_prints"></label><label id="lb_cu_icon_gran_total"></label></td>
												</tr>
												<tr style="font-size: 8px;">
													<td></td>
													<td></td>
													<td><?php echo $tr->translate('PAYMENT_AMOUNT') ?>:</td>
													<td style="" align="center"><label id="lb_gran_pay_prints"></label><label id="lb_cu_icon_gran_pay"></label></td>
												</tr>
												<tr style="font-size: 8px;">
													<td></td>
													<td></td>
													<td><?php echo $tr->translate('BALANCE') ?>:</td>
													<td style="" align="center"><label id="lb_balance_prints"></label><label id="lb_cu_icon_balances"></label></td>
												</tr>
                                                <tr>
                                                	<div style="padding-top:1px;"></div>
                                                	<td align="left" style="font-size:8px"> <p> Customer's Signature </p> <p> ហត្ថលេខាអ្នកទិញ </p> </td>
                                                    <td></td>
                                                    <td></td>
                                                    <td align="center" style="font-size:8px"><p> Seller's Signature </p> <p> ហត្ថលេខាអ្នកលក់​</p></td>
                                                </tr>
											</table>
										</div>
								    </div>
			                </div>
			            </div> 
		            </div>       
	            </div>          
	        </div>                  
	    </div>
    </div>  
</form>
<script type="text/javascript">
jQuery(document).ready(function(){
	
	if(index5==0){
		template='<tr id="row_order_'+index5+'" style="height:33px;" >';
		template+='<td colspan="5" align="center">No Record Selected !<td>';
		template+="</tr>";
		$('#order_item').append(template);
	}
	   getRate();
	  // $('#add_item').focus();
	 // $('#add_item').chosen().filter('[autofocus]').trigger('chosen:activate');
	   //$('#add_item').trigger('chosen:activate');
});
	
	function submitData(){
	   var data = $("#order_form").serialize();
		var url_submit = '<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'ajax-add-order')); ?>';
		$.ajax({
			type:'post',
	   		url:url_submit,
	   		data:data,
	   		success: function(data){
					window.location.href ="<?php echo $this->baseUrl();?>/index/pos";
				},
				error: function(e) {
					window.location.href ="<?php echo $this->baseUrl();?>/index/pos";
				}
			});
	}
   function deleteRecord(index) {
		var id_record = $('#identity').val();
		var arrays = id_record.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		$("#row_order_"+index).remove();
		//$("#row_order_update_"+index).remove();
		calculateGrandTotal();
		$('#add_item').focus();
	}

  /* $("a[id=order_id]").on("click", function () { 
	    var a = $(this).data('index');
	    $('#update_id').val(a);
	    getOrder(a); 
	});*/
	function tempAlert(msg,duration){
		 var el = document.createElement("div");
		 el.setAttribute("style","position:absolute;top:30%;left:45%;background-color:white; color:red;font-size:16px;padding:5%;");
		 el.innerHTML = msg;
		 setTimeout(function(){
		  el.parentNode.removeChild(el);
		 },duration);
		 document.body.appendChild(el);
	}
   function getItemOrder(){
		item_ids=$("#add_item").val();
		if(item_ids==-1){
			return false;
		}
		addRow(item_ids);
		/*var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'get-qty-warning'));?>";
		   $.ajax({
		        url: url,
		        type: "post",
		        data: {'id':item_ids},
		        success: function(data){
		            val = $.parseJSON(data);
					if(val<=0){
						var msg = "ផលិតផលអស់ពីស្តុក!";
						tempAlert(msg,3000);
						//alert("ផលិតផលអស់ពីស្តុក!" );
						return false;
					}else{
						
					}
		        },
		        error:function(e){
		            alert(e);
		        }
		    });*/
		
		$("#add_item").val("");
		
	}
   pqty = 1;
   var index5 = 0;num=0;
   var template = '';
   var value = '';
   
   function addRow(item_id) {
	   index5++;
	   
		for(var i=1; i<index5; i++){
			new_item=parseInt(item_id);
			items = parseInt($("#item_id"+i).val());
			if(new_item==items){
				newqty = parseInt($("#qty"+i).val());
				newqty = newqty+1;
				$("#qty"+i).val(newqty);
				//doTotalPriceUnitQty(i);
				doTotalPricePerQty(i);
				return false;
			}
			
		}
		if(num>=15){
				alert('វិក័យប័ត្រមានត្រឹមតែ 15 ទេ សូមចេញវិក័យប័ក្រ​មួយផ្សេងទៀត');
				return false;
		}
		var no = $('#identity').val();
		if(no == ""){
			no = 1;
			
		}else{
			number = $('#identity').val();
		    var arrays = number.split(',');
			inx = 1;
			for(var index=0;index<arrays.length;index++) {
				no=index+inx+1;
				//alert(no);
			}
		}
		num++;
   		template='<tr class="row_order" id="row_order_'+index5+'" style="height:33px;">';
	   	template+='<td>'+no+'</td>';
	   	template+='<td><span style="cursor:pointer" onclick="deleteRecord('+i+')" class="icon-trash"></span></td>';
	   	template+='<td><input type="hidden" id="item_id'+index5+'" name="item_id'+index5+'" /><labe id="lb_item_name_'+index5+'"></label></td>';
	   	
		//template+='<td><input type="text" onBlur="doTotalPriceUnitQty('+index5+');" class="validate[required,custom[number]] input" value="1" id="unit_qty'+index5+'" name="unit_qty'+index5+'"/><input type="hidden" id="qty_per_unit_'+index5+'" name="qty_per_unit_'+index5+'" /></td>';
		//template+='<td><input type="hidden" id="cu_id_'+index5+'"><input type="hidden" id="rate_'+index5+'"><input type="text" class="validate[required]" id="unit_price'+index5+'" name="unit_price'+index5+'" /><input type="hidden" id="sub_total_unit_'+index5+'" name="sub_total_unit_'+index5+'" /></td>';
		
	   	template+='<td><input type="text" onBlur="doTotalPricePerQty('+index5+');" class="validate[required,custom[number]] input" value="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
		template+='<td><input type="hidden" id="cu_id_'+index5+'"><input type="hidden" id="rate_'+index5+'"><input type="text" class="validate[required]" id="price_per_qty'+index5+'" name="price_per_qty'+index5+'" /><input type="hidden" id="sub_total_qty_'+index5+'" name="sub_total_qty_'+index5+'" /></td>';
		
	   	template+='<td><input type="hidden" class="input" readonly="readonly"  id="total_price'+index5+'" name="total_price'+index5+'" /></span><label id="cu_id_icon'+index5+'" style="float:left;"></label><div style="float:right;" id="lb_total_price_'+index5+'"></div><input type="hidden" id="total_qty'+index5+'" name="total_qty'+index5+'" /></td>';
	   	template+="</tr>";
   	$('#order_item').append(template);
   	if(index5!=1) {
		var id = $('#identity').val();
		$('#identity').val(id+','+index5);
	} else {$('#identity').val(index5);}
   	$("#item_id_"+index5).val(item_id);
   	$("#row_order_0").remove();
   	$(".odd").remove();
	getProduct(item_id,index5);
	$('#add_item').focus();
   }
   function getProduct(id,indexs){
	   var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'get-product-by-id'));?>";
		//var id = $("#").val();
	   $.ajax({
		        url: url,
		        type: "post",
		        data: {'id':id},
		        success: function(data){
		            val = $.parseJSON(data);
		            
		            val = $.parseJSON(data);
		            	qty_onhand = val.qty_onhand;
		            	
			           // unit_price = val.unit_sale_price;
			         	price_per_qty = val.price_per_qty;
			         	item_name_kh = val.name_kh;
			         	item_name_en = val.name_en;
			         	item_size = val.item_size;
			         	item_id = val.pro_id;
			            cu_id = val.cu_id;
						//qty_perunit = val.qty_perunit;
			            rate = val.rate;
			            cu_icon = val.icon;
						$("#item_id"+indexs).val(item_id);
						$('#cu_id_'+indexs).val(cu_id);
						$('#rate_'+indexs).val(rate);
						document.getElementById('cu_id_icon'+indexs).innerHTML =val.icon;
						document.getElementById('lb_item_name_'+indexs).innerHTML = item_name_kh+" ("+item_size+")"+",<br />"+item_name_en+ " ("+item_size+")";
			            //$("#unit_price"+indexs).val(parseFloat(unit_price));
			         	$("#price_per_qty"+indexs).val(parseFloat(price_per_qty));
						//$('#qty_per_unit_'+indexs).val(qty_perunit);

						/*if(qty_onhand<=<?php echo $qty_warning?>){
			            	alert("ផលិតផលជិតអស់ពីស្តុក! សល់ត្រឹមតែ "+qty_onhand);
		            	}*/
			         	//doTotalPriceUnitQty(indexs);
			        	doTotalPricePerQty(indexs);
		        },
		        error:function(e){
		            alert(e);
		        }
		    });
   }
   function clearAjaxData(){
	   $('.row_order').remove();
	   $('#subtotal_order_update').remove();
	   $('#subtotal_order').remove();
   }
   function doTotalPriceUnitQty(index){
	   qty_unit = parseFloat($("#unit_qty"+index).val());
	   unit_price = parseFloat($("#unit_price"+index).val());
	   total = qty_unit * unit_price;
	   $('#sub_total_unit_'+index).val(total);
	   doTotalQty(index);
	   doAmountPrice(index);
	  // $('#add_item').focus();
   }
   function doTotalPricePerQty(index){
	   qty = parseFloat($("#qty"+index).val());
	   price_per_qty = parseFloat($("#price_per_qty"+index).val());
	   total = qty * price_per_qty;
	   $('#sub_total_qty_'+index).val(total.toFixed(2));
	   doTotalQty(index);
	   doAmountPrice(index);
	  // $('#add_item').focus();
   }
   function doAmountPrice(index){
	  // unit_price = $('#sub_total_unit_'+index).val();
	   price_per_qty = parseFloat($('#sub_total_qty_'+index).val());

	   //total_amount = parseFloat(unit_price) + parseFloat(price_per_qty);
	   $('#total_price'+index).val(price_per_qty.toFixed(2));
	   document.getElementById('lb_total_price_'+index).innerHTML=price_per_qty.toFixed(2);
	   getRate();
	   //$('#add_item').focus();
   } 
   function doTotalQty(index){
	  // qty_unit = $('#unit_qty'+index).val();
	  // qty_per_unit = $('#qty_per_unit_'+index).val();
	   qty = $('#qty'+index).val();
	   //total_qty = (parseFloat(qty_unit)*parseFloat(qty_per_unit))+parseFloat(qty);
	   $('#total_qty'+index).val(qty);
	 //  $('#add_item').focus();
   }
   function calculateGrandTotal(){
	   var rate = parseFloat($('#rate').val());
	   var grand_total = 0;
	   
	   var id = $('#identity').val();
	   var arrays = id.split(',');
		for(var index=0;index<arrays.length;index++) {
			var price = $('#total_price'+arrays[index]).val();
			grand_total = (grand_total + parseFloat(price));
		}
		total= grand_total*rate;
		$('#gran_total').val(total.toFixed(2));
		$('#gran_pay').val(total.toFixed(2));
		//$('#add_item').focus();
   }
   function getRate(){
	   var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'get-rate'));?>";
	   var from_cu = $('#currency_setting').val();
	   var to_cu = $('#currency').val();
	   if(from_cu==to_cu){
		   $('#rate').val(1);
		   calculateGrandTotal();
	   }else{
		   $.ajax({
		        url: url,
		        type: "post",
		        data: {'from_cu':from_cu,'to_cu':to_cu},
		        success: function(data){
		            val = $.parseJSON(data);
					$('#rate').val(val);
					calculateGrandTotal();
		        },
		        error:function(e){
		            alert(e);
		        }
		    });
		}
		getCurrencyIcon();
   }
   
   function getCurrencyIcon(){
	   var url = "<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'get-currency-icon'));?>";
	   var cu_id = $('#currency').val();
		   $.ajax({
		        url: url,
		        type: "post",
		        data: {'cu_id':cu_id},
		        success: function(data){
		            val = $.parseJSON(data);
					document.getElementById('cu_icon_gran_total').innerHTML=val;
					document.getElementById('cu_icon_gran_pay').innerHTML=val;
					document.getElementById('cu_icon_balance').innerHTML=val;
		        },
		        error:function(e){
		            alert(e);
		        }
		    });
   }
   function doBalance(){
	   var total_pay = $('#gran_pay').val();
	   var gran_total = $('#gran_total').val();
	   
	   balance = parseFloat(gran_total) - parseFloat(total_pay);
	   $('#balance').val(balance.toFixed(2));
	   $('#add_item').focus();
   }
   
   function itemTaplePrint(){
	   var invoice_no = $('#saleorder_no').val();
	   var date = $('#datepicker').val();
	   var customer = $('#customer').find(":selected").text();
	   var user = '<?php echo $user;?>';
	   var grand_total =$('#gran_total').val();
	   var gran_pay = $('#gran_pay').val();
	   var balance = $('#balance').val();
	   var currency = $('#currency option:selected').html();
	   var id = $('#identity').val();
	   
	  
	   
		var splitdate = date.split("-");
		year = splitdate[0];
		month = splitdate[1];
		day = splitdate[2];
		
		var dateString = day+'-'+month+'-'+year;
		
		
	   var cu_icon_raw = document.getElementById('cu_icon_gran_total');
	   cu_icon_f =(cu_icon_raw.innerText || cu_icon_raw.textContent);
	   document.getElementById('lb_order_no').innerHTML=invoice_no;
	   document.getElementById('lb_date').innerHTML=dateString;
	   document.getElementById('lb_customer').innerHTML=customer;
	   //document.getElementById('lb_cashier').innerHTML=user;
	   document.getElementById('lb_gran_total_print').innerHTML=grand_total+" "+cu_icon_f;
	   document.getElementById('lb_gran_pay_print').innerHTML=gran_pay+" "+cu_icon_f;
	   document.getElementById('lb_balance_print').innerHTML=balance+" "+cu_icon_f;
	   document.getElementById('lb_cu_type').innerHTML=currency;
	   var arrays = id.split(',');
	 
		for(var index=0;index<arrays.length;index++) {
			num = index+1;
			var item_name = document.getElementById('lb_item_name_'+arrays[index]);
			//var qty_unit = $('#unit_qty'+arrays[index]).val();
			var qty_per_unit = $('#qty'+arrays[index]).val();
			//var unit_price = $('#unit_price'+arrays[index]).val();
			var price_per_qty = $('#price_per_qty'+arrays[index]).val();
			var sub_total = $('#total_price'+arrays[index]).val();
			 var icon_raw = document.getElementById('cu_id_icon'+arrays[index]);
			 icon = (icon_raw.innerText || icon_raw.textContent);
			item_raw = (item_name.innerText || item_name.textContent);
			item_text = item_raw.split(",");
			print_item='<tr class="odd gradeX" style=" font-size: 8px; border-collapse: collapse; line-height:27px">';
			print_item+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;">'+num+'</td>';
			print_item+='<td style="border: 1px solid #272222; border-collapse: collapse;padding-left:5px;"><labe id="lb_item_name_print'+arrays[index]+'">'+item_text[0]+'-'+item_text[1]+'</label></td>';			
			//print_item+='<td style="border: 1px solid #272222;text-align: center; border-collapse: collapse;"><label id="lb_qty_unit_print'+arrays[index]+'">'+qty_unit+'</label></td>';
			//print_item+='<td style="border: 1px solid #272222;text-align: center;margin: 1px;"><label id="lb_unit_price_price'+arrays[index]+'">'+unit_price+'</label></td>';			
			print_item+='<td style="border: 1px solid #272222;text-align: center; border-collapse: collapse;"><label id="lb_qty_print'+arrays[index]+'">'+qty_per_unit+'</label></td>';
			print_item+='<td style="border: 1px solid #272222;text-align: center; border-collapse: collapse;"><label id="lb_price_per_qty_print"></label>'+price_per_qty+'</td>';			
			print_item+='<td style="border: 1px solid #272222;text-align: center; border-collapse: collapse;"><label id="lb_total_price_print'+arrays[index]+'">'+sub_total+'</label><label>'+icon+'</label></td>';
			print_item+="</tr>";
			$('#order_item_print').append(print_item);
		}
		if(arrays.length<15){
				var count = arrays.length;
				for(i=1;i<15-count;i++){
					inx = i+1;
					x = num+i;
					print_items='<tr class="odd gradeX" style=" font-size: 8px; border-collapse: collapse;height: 28px;">';
					print_items+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;">'+x+'</td>' ;
					print_items+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid #272222;text-align: center;border-collapse: collapse;"></td>' ;
					print_items+="</tr>";
					$('#order_item_print').append(print_items);
				}
				
		}
		
   }
   function itemOwnerPrint(){
	   var invoice_no = $('#saleorder_no').val();
	   var date = $('#datepicker').val();
	   var customer = $('#customer').find(":selected").text();
	   var user = '<?php echo $user;?>';
	   var grand_total =$('#gran_total').val();
	   var gran_pay = $('#gran_pay').val();
	   var balance = $('#balance').val();
	   var currency = $('#currency option:selected').html();
	   var customer = $('#customer').find(":selected").text();
	   var id = $('#identity').val();
		var splitdate = date.split("-");
		year = splitdate[0];
		month = splitdate[1];
		day = splitdate[2];
		
		var dateString = day+'-'+month+'-'+year;
		
		
	   var cu_icon_raw = document.getElementById('cu_icon_gran_total');
	   cu_icon_f =(cu_icon_raw.innerText || cu_icon_raw.textContent);
	   document.getElementById('lb_order_nos').innerHTML=invoice_no;
	   document.getElementById('lb_dates').innerHTML=dateString;
	   //document.getElementById('lb_customer').innerHTML=customer;
	   //document.getElementById('lb_cashier').innerHTML=user;
	   document.getElementById('lb_gran_total_prints').innerHTML=grand_total+" "+cu_icon_f;
	   document.getElementById('lb_gran_pay_prints').innerHTML=gran_pay+" "+cu_icon_f;
	   document.getElementById('lb_balance_prints').innerHTML=balance+" "+cu_icon_f;
		document.getElementById('lb_customers').innerHTML=customer;
	   document.getElementById('lb_cu_types').innerHTML=currency;
	   var arrays = id.split(',');
		for(var index=0;index<arrays.length;index++) {
			num = index+1;
			var item_name = document.getElementById('lb_item_name_'+arrays[index]);
			var qty_unit = $('#unit_qty'+arrays[index]).val();
			var qty_per_unit = $('#qty'+arrays[index]).val();
			var unit_price = $('#unit_price'+arrays[index]).val();
			var price_per_qty = $('#price_per_qty'+arrays[index]).val();
			var sub_total = $('#total_price'+arrays[index]).val();
			 var icon_raw = document.getElementById('cu_id_icon'+arrays[index]);
			 icon = (icon_raw.innerText || icon_raw.textContent);
			item_raw = (item_name.innerText || item_name.textContent);
			item_text = item_raw.split(",");
			print_item='<tr class="odd gradeX" style=" font-size: 9px; border-collapse: collapse; line-height:27px;">';
			print_item+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;">'+num+'</td>';
			print_item+='<td style="border: 1px solid rgb(111, 182, 251); border-collapse: collapse;"><labe id="lb_item_name_print'+arrays[index]+'">'+item_text[0]+'-'+item_text[1]+'</label></td>';		
			print_item+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center; border-collapse: collapse;"><label id="lb_qty_print'+arrays[index]+'">'+qty_per_unit+'</label></td>';
			print_item+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center; border-collapse: collapse;"><label id="lb_price_per_qty_print"></label>'+price_per_qty+'</td>';			
			print_item+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center; border-collapse: collapse;"><label id="lb_total_price_print'+arrays[index]+'">'+sub_total+'</label><label>'+icon+'</label></td>';
			print_item+="</tr>";
			$('#order_item_owner').append(print_item);
		}
		if(arrays.length<15){
				var count = arrays.length;
				for(i=1;i<15-count;i++){
					
					inx = i+1;
					x = num+i;
					print_items='<tr class="odd gradeX" style=" font-size: 8px; border-collapse: collapse;height: 28px;">';
					print_items+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;">'+x+'</td>' ;
					print_items+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;"></td>' ;
					print_items+='<td style="border: 1px solid rgb(111, 182, 251);text-align: center;border-collapse: collapse;"></td>' ;
					print_items+="</tr>";
					$('#order_item_owner').append(print_items);
				}
				
		}
		
   }
   function Clickheretoprint()
   { 
			var identity = $('#identity').val();
			if(identity==""){
				alert("គ្មានផលិតផលសម្រាប់បោះពុម្ព");
			}else{
   itemTaplePrint();
		     var disp_setting="toolbar=yes,location=no,directories=yes,menubar=yes,"; 
		         disp_setting+="scrollbars=yes,width=600, height=500, left=100, top=25"; 
		     var content_vlue = document.getElementById("printShow").innerHTML; 
		     
		     var docprint=window.open("","",disp_setting); 
		      docprint.document.open(); 
		      docprint.document.write('<html><head><title>Group</title>'); 
		      docprint.document.write('</head><body onLoad="self.print()" style=" padding:10px; margin:0px; font-family:Verdana; font-size:10px;"><center>');          
		      docprint.document.write(content_vlue);          
		      docprint.document.write('</center></body></html>'); 
		      docprint.document.close(); 
		      docprint.focus(); 
			  
		      hideDialog();
			  printOwner();
			  submitData();
			}
   }
   function hideDialog() {		
		$("#printShow").hide();
	}
	
	function printOwner()
   { 
	   itemOwnerPrint();
		     var disp_setting="toolbar=yes,location=no,directories=yes,menubar=yes,"; 
		         disp_setting+="scrollbars=yes,width=600, height=500, left=100, top=25"; 
		     var content_vlue = document.getElementById("printForOwner").innerHTML; 
		     
		     var docprint=window.open("","",disp_setting); 
		      docprint.document.open(); 
		      docprint.document.write('<html><head><title>Group</title>'); 
		      docprint.document.write('</head><body onLoad="self.print()" style=" margin:0px;padding:10px; font-family:Verdana; font-size:10px; background:rgba(204, 106, 120, 0.23) !important;"><center>');          
		      docprint.document.write(content_vlue);          
		      docprint.document.write('</center></body></html>'); 
		      docprint.document.close(); 
		      docprint.focus();
		     // submitData(); 
		      OnwerhideDialog();
   }
   function OnwerhideDialog() {		
		$("#printForOwner").hide();
		
	}
   </script>
            