<?php $frmuser = $this->frmusers;
$cancel_url = $this->url(array('module'=>'users','controller'=>'index','action'=>''),null,true);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
dt{ display: none;}
.btn{ margin-right: 5px!important;margin-left: 5px!important;} 
.breadCrumb{ margin-top:5px;}
</style>
<form id="validate" enctype="multipart/form-data" method="post">
    <div class="content">                
        <div class="row-fluid">           
            <div class="span12" style="margin:0 auto;">                                
                <div class="widget">
                    <div class="head">
                        <div class="icon"><i class="icosg-bookmark1"></i></div>
                        <h2><?php echo $tr->translate('FORM_ADD') ?></h2>
                    </div>                                            
                    
                    <div class="block-fluid">
                        <div class="row-form">
                            <div class="span2"><?php echo $tr->translate('ID_CODE') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('id_code');?>
                            </div>
                            <div class="span2"><?php echo $tr->translate('FULL_NAME') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('fullname');?>
                            </div>
                        </div>    
                        <div class="row-form">
                            <div class="span2"><?php echo $tr->translate('USER_NAME') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('username');?>
                            </div>
                            <div class="span2"><?php echo $tr->translate('EMAIL') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('email');?>
                            </div>
                        </div> 
                        <div class="row-form">
                            <div class="span2"><?php echo $tr->translate('PASSWORD') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('password');?>
                            </div>
                            <div class="span2"><?php echo $tr->translate('CONFIRM_PASSWORD') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('confirm_password');?>
                            </div>
                        </div> 
                        <div class="row-form">
                            <div class="span2"><?php echo $tr->translate('STATUS') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('status');?>
                            </div>
                            <div class="span2"><?php echo $tr->translate('USER_TYPE') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('user_type');?>
                            </div>
                        </div> 
                        
                        <div class="row-form">                 
                        	<div class="span2"><?php echo $tr->translate('CAT_NAME_ICON') ?>:</div>
	                        <div class="span4">
			                	<div class="fileupload fileupload-new pull-left" data-provides="fileupload">
			                         <div class="fileupload-new thumbnail" style="width: 50px; height: 50px;">
			                             <img src="<?php echo $this->baseUrl();?>/img/noimg_s.gif"/>
			                         </div>
			                       	<div class="fileupload-preview fileupload-exists thumbnail" style="width: 50px; height: 50px;"></div>
			                        	<span class="btn btn-file btn-primary">
			                         	<span class="fileupload-new">Select image</span>
			                         	<span class="fileupload-exists">Change</span><input type="file" name="photo" />
			                         	</span>
			                          	<a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
			                 	</div>                        
	                                <?php //echo $frmcate->getElement('icon');?>
                            </div>              
                            <div class="span6" class="toolbar bottom TAR" style="margin-top:20px;">
                                 <div class="btn-group pull-right" style="margin-top:2px;">
                                   <button  type="submit" id="save" name="save" class="btn btn-primary btn-sm btn-grad"><i class="icon-share icon-white"> </i><?php echo $tr->translate('SAVE') ?></button>
                                  <button style=" margin-right: 5px!important;" type="submit" id="save_close" name="save_close" class="btn btn-primary btn-sm btn-grad"><i class="icon-share icon-white"> </i> <?php echo $tr->translate('SAVE_CLOSE') ?></button>                        		
                                  <a href="<?php echo $cancel_url; ?>"><button type="button" class="btn btn-danger btn-sm btn-grad"><i class="icon-remove-sign icon-white"> </i><?php echo $tr->translate('CANCEL') ?></button></a>  	
                                </div> 
                            </div>
                        </div>
                    </div>                 
                </div>
            </div>
        </div>                        
    </div>  
</form>
<script>
<?php $getfillter_add =  $this->url(array('module'=>'users','controller'=>'index','action'=>'getfillteradd')); ?>
function getfillterUserType(){
	username = $('#username').val();
	$.ajax({
		url:"<?php echo $getfillter_add;?>",
		type:"post",
		data:{'username':username},
		success: function(data){	
			user= $.parseJSON(data);					
			if(user!=null){
				 for (var index = 1; index <= username.length; index++) {
					 alert(username[index-1]['username']+" is Already Exist!!");
				}
				 document.getElementById("username").style.borderColor="#FF0000";
				 document.getElementById("username").style.color="#FF0000";
				 document.getElementById("save").setAttribute('disabled', 'disabled');
				 document.getElementById("save_close").setAttribute('disabled', 'disabled');
			}else{
				document.getElementById("save").disabled = false;
				document.getElementById("save_close").disabled = false;
				document.getElementById("username").style.borderColor="";
				document.getElementById("username").style.color="#000";
			}
		},
		error:function(){
		}
	});
}
</script>