<?php $frmuser = $this->frmusers;
$cancel_url = $this->url(array('module'=>'users','controller'=>'index','action'=>''),null,true);
$cancel_url_change = $this->url(array('module'=>'users','controller'=>'index','action'=>'change-password'),null,true);
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<style>
dt{ display: none;}
.btn{ margin-right: 5px!important;margin-left: 5px!important;} 
.breadCrumb{ margin-top:5px;}
</style>
    <div class="breadCrumb clearfix">    
        <ul id="breadcrumbs">
            <li><a href="index.html">Home</a></li>
            <li><a href="<?php echo $this->baseUrl();?>/users"><?php echo $tr->translate('USER') ?></a></li>
            <li><?php echo $tr->translate('ADD') ?></li>
        </ul>        
    </div>
<form id="validate" enctype="multipart/form-data" method="post">
    <div class="content">                
        <div class="row-fluid">           
            <div class="span12" style="margin:0 auto;">                                
                <div class="widget">
                    <div class="head">
                        <div class="icon"><i class="icosg-bookmark1"></i></div>
                        <h2><?php echo $tr->translate('FORM_CHANGE') ?></h2>
                    </div>                                            
                    <div class="block-fluid">
                        <div class="row-form">
                            <div class="span2"><?php echo $tr->translate('OLD_PASSWORD') ?> :</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('old_password');?>
                            </div>
                            <div class="span2"><?php echo $tr->translate('PASSWORD') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('password');?>
                            </div>
                            
                        </div>
                        <div class="row-form">
                        	<div class="span2"><?php echo $tr->translate('CONFIRM_PASSWORD') ?>:</div>
                            <div class="span4">
                                <?php echo $frmuser->getElement('confirm_password');?>
                            </div>                           
                            <div class="span6" class="toolbar bottom TAR" >
                                <div class="btn-group pull-right" style="margin-top:2px;"> 
                                  <button type="submit" id="save" name="save" class="btn btn-primary btn-grad"><i class="icon-share icon-white"> </i> <?php echo $tr->translate('SAVE') ?></button>
	                        	<button type="submit" id="save_close" name="save_close" class="btn btn-primary btn-grad"><i class="icon-share icon-white"> </i> <?php echo $tr->translate('SAVE_CLOSE') ?></button>                        		
	                        	<a href="<?php echo $cancel_url; ?>"><button​ type="button" class="btn btn-primary btn-grad"><i class="icon-remove-sign icon-white"> </i> <?php echo $tr->translate('CANCEL') ?></button></a> 
                            </div>
                        </div>
                    </div>                 
                </div>
            </div>
        </div>                        
    </div>  
</form>