<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$product = $this->getdata;
	$order = $this->order;
	$frm = $this->frm;
	$FrmOrderUpdate =$this->FrmOrderUpdate;
	//print_r($product);
	$session = new Zend_Session_Namespace('auth');
	$user = $session->fullname;
?>
<style>
dt{ display: none;}
.btn{ margin-right: 5px!important;margin-left: 5px!important;} 
.breadCrumb{ margin-top:5px;}
</style>
<script src="<?php echo $this->baseUrl();?>/js/atn-cart.js"></script>
<form enctype="multipart/form-data" method="post">
    <div class="content">      
        <div class="row-fluid">  
            <div class="span6">                

                <div class="widget">
                    <div class="head dark">
                        <div class="icon"><i class="icos-home"></i></div>
                        <h2><?php echo $tr->translate('MENU') ?></h2>
                    </div>
                    <div class="block-fluid">
                    <h4 style="text-align: center;"><?php echo $tr->translate('STEAMED_NOODLE'); ?></h4>
						<div class="middle">    
						<?php 
						$script_products ="";
						$script_product_prices="";
						$script_proId="";

							foreach ($product as $rs){
								$script_products.="products[".($rs["pro_id"])."]=\"".($rs["pro_name_en"])."\";\n";
								$script_proId.="proId[".($rs["pro_id"])."]=\"".($rs["pro_id"])."\";\n";
								$script_product_prices.="product_prices[".($rs["pro_id"])."]=\"".($rs["price_out"])."\";\n";
						?>
						
			                <div class="informer">
			                    <a href="javascript:AddToCart(<?php echo $rs["pro_id"];?>)">
			                    	
			                        <span><img alt="" src="<?php echo $this->baseUrl();?>/icon/<?php echo $rs["icon"]?>" width="118px" height="115px"></span>
			                        <span class="name"><?php echo $rs["pro_name_en"];?></span>
			                        <span class="price"><?php echo $rs["price_out"]; ?></span>
			                        
			                    </a>
			                </div>
						<?php }?>
			            <script>
							//var currency_symbol="<?php //echo $currency_symbol;?>";
							
							var products=Array();
							<?php echo $script_products;?>
							var proId=Array();
							<?php echo $script_proId;?>
							var product_prices=Array();
							<?php echo $script_product_prices;?>
						</script>       
			            </div><!-- end -->			       
                    </div>
                    
                </div>
            </div>
            
            
            
            <div class="span6">                
				<div class="widget">
                    <div class="head dark">
                        <div class="icon"><i class="icos-newtab"></i></div>
                        <h2>Order & Invoice </h2>
                    </div>  
                    <div class="block-fluid tabbable">                    
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="#tab1" data-toggle="tab">
                            	<i class="icon-tags"></i> <?php echo $tr->translate('ORDER'); ?>
                            </a></li>
                            <li><a href="#tab2" data-toggle="tab"><i class="icon-list"></i> <?php echo $tr->translate('LIST_INVOCE'); ?></a></li>
                        </ul>
                        <div class="tab-content">
                            <div class="tab-pane active" id="tab1">
                            	<div id="popup" class="alert alert-warning"></div>
	                            <div class="block-fluid">
	                            	<div class="row-form">
	                            		<div class="span2"></div>
			                            <div class="span4"></div>
			                            <div class="span2"><?php echo $tr->translate('ORDER_NO') ?>:</div>
			                            <div class="span4"><?php echo $frm->getElement('order_no');?></div> 
	                            	</div>
		                            <div class="row-form">
			                            <div class="span2"><?php echo $tr->translate('TABLE') ?>:</div>
			                            <div class="span4">
			                                <?php echo $frm->getElement('table');?>
			                            </div>
			                            <div class="span2"><?php echo $tr->translate('DATE') ?>:</div>
			                            <div class="span4">
			                            	<div class="input-prepend input-append">
				                                <?php echo $frm->getElement('date');?>  
				                                <span class="add-on" style="right"><i class="icon-calendar"></i></span>                              
				                          </div>  
			                                <?php //echo $frm->getElement('dates');?>
			                            </div>
			                        </div>
			                        <div class="row-form">
			                            <div id="Cart">
											The cart is empty!
										</div>
										<input type="hidden" name="identity" id="identity">
			                        </div>
			                        
			                        <div class="row-form">
			                        
			                            <div class="span12">
			                            	<button type="submit" class="btn btn-primary btn-sm btn-grad"><i class="icon-share icon-white"></i> Save</button>
			                            	<button type="button" class="btn btn-success" Onclick="Clickheretoprint();"><i class="icon-print icon-white"></i> Save & Print</button>
			                            	<button class="btn btn-danger"><i class="icon-remove icon-white"></i> Cancel</button>
			                            	
			                            </div>
			                        </div>
			                    </div> 
			                    
			                    <div class="row-fluid" style="display: none">
			                    	<div  id="printShow" style="display: block;">
			                    		<div class="row-form" style="width:100%; padding:0;">
			                    			<div class="span6" style="width:40%; padding:0;"><img alt="" src="<?php echo $this->baseUrl();?>/logo.png" width="60px" style="margin-right: 10px;">Welcome for come here</div>
			                    		</div>
			                    		<div style="height: 20px; clear:both;" ></div>
			                    		<div class="row-form" style="width:100%; padding:0;">
			                    		<table style="width: 100%; border: 0;position: relative;padding: 0px;margin: 0px;border-spacing: 0px;border-collapse: collapse;">
			                    			<tr class="odd gradeX" style="font-size: 9px;">
			                    				<td width="20%"></td>
			                    				<td width="30%"></td>
			                    				<td style="width:20%"><label>Reciept No :</label></td>
			                    				<td align="right" width="30%"><label  for="myalue" id="lb_reciept"></label></td>
			                    			</tr>
			                    			<tr class="odd gradeX" style="font-size: 9px;">
			                    				<td><label id="lb_cashier">Cashier :</label></td>
			                    				<td><label id="lb_cashier_name"></label></td>
			                    				<td style=""><label>Table :</label></td>
			                    				<td align="right"><label  for="myalue" id="lb_table"></label></td>
			                    			</tr>
			                    			<tr class="odd gradeX" style="font-size: 9px;">
			                    				<td></td>
			                    				<td></td>
			                    				<td style=""><label>Date :</label></td>
			                    				<td align="right"><label id="lb_date"></label><td>
			                    			</tr>
			                    		</table>
			                    		</div>
			                    		<div style="height: 20px;"></div>
			                    		<div id="print">
				                        	Cart is Empty
			                    		</div>
			                    		</div>
			                        </div> 
		                    </div>
                            <div class="tab-pane" id="tab2">
                               <div class="widget">
				                <div class="head">  
				                    <div class="btn-group pull-left">
				                    	<h2><span class="icon-th"></span>Table </h2>   
				                    </div>
				                     <div class="panel panel-default">
				                                <div class="panel-heading">
				                                    <div class="btn-group pull-right" style="margin-top:2px;">
				                                        <button class="btn dropdown-toggle" data-toggle="dropdown"><i class="icon-print"></i> <?php echo $tr->translate('PRINT');?></button>
				                                    </div>                                    
				                                </div>                    
				               		 </div>
				                <div style="clear:both"></div>
				                <div class="panel-body">                
				                    <div class="block-fluid">
				                        <table class="fpTable datatable" cellpadding="0" cellspacing="0" width="100%" id="customers2">
				                            <thead>
				                                <tr>
				                                    <th width="25%">Order Number</th>
				                                    <th width="20%">Table</th>
				                                    <th width="20%">Total Amount</th>
				                                    <th width="20%">Cashier</th>
				                                    <th width="15%" class="TAC">Date</th>
				                                </tr>
				                            </thead>
				                            <?php if($order!=""){
				                            		foreach ($order as $row){ ?>
														<tbody>
							                                <tr>
							                                    <td><a id="order_id" href="#fModal" data-toggle="modal" data-index="<?php echo $row["so_id"]?>"><?php echo $row["order_no"];?></a></td>
							                                    <td><?php echo $row["name_en"];?></td>
							                                    <td><span class="label label-important"><?php echo $row["total"];?></span></td>
							                                    <td><?php echo $user;?></td>
							                                    <td><?php echo $row["date"];?></td>
							                                </tr>
							                             </tbody>
											<?php }
				                            }?>
				                        </table>                    
				                    </div> 
				           		</div>
				           		<div id="fModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="overflow: hidden; width:70%;left:34%;" >
					            
					            <div class="modal-dialog">
    							<div class="modal-content">
					            <div class="modal-header">
					                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
					                <h3 id="myModalLabel">Modal form</h3>
					            </div>
					            <div class="modal-body">        
					            <div class="row-fluid">
					                <div class="block-fluid">
					                    <div class="row-form">
	                            		<div class="span2"></div>
			                            <div class="span4"></div>
			                            <div class="span2"><?php echo $tr->translate('ORDER_NO') ?>:</div>
			                            <div class="span4"><?php echo $FrmOrderUpdate->getElement('order_nos');?></div> 
	                            	</div>
		                            <div class="row-form">
			                            <div class="span2"><?php echo $tr->translate('TABLE') ?>:</div>
			                            <div class="span4">
			                                <?php echo $FrmOrderUpdate->getElement('tables');?>
			                            </div>
			                            <div class="span2"><?php echo $tr->translate('DATE') ?>:</div>
			                            <div class="span4">
				                                <?php echo $FrmOrderUpdate->getElement('dates');?>  
			                            </div>
			                        </div>
			                        <div class="row-form">
			                            <div class="span2"><?php echo $tr->translate('PRODUCT') ?>:</div>
			                            <div class="span10">
			                            	<select id="add_item" name="add_item" onChange="getItemOrder();" class="" tabindex="4">
												<?php echo $this->itemsOption; ?>
											</select>
			                                <?php //echo $FrmOrderUpdate->getElement('product');?>
			                            </div>
			                        </div>
					                    
					                    <div class="row-form">
							                    <table cellpadding="0" cellspacing="0" width="100%" id="order_item">
							                    	<thead>
													<tr style="font-weight: bold;">
														<td>No</td>
														<td>Item Description</td>
														<td>Unit Price</td>
														<td>Qty</td>
														<td>Amount</td>
														<td></td>
													</tr>
													</thead>
												</table> 
											<div id="subtotal">
											</div>
										</div>     
					                </div>
					            </div>  
					            <input type="text" id="id_record" name="id_record"/>
					            </div>                 
					            <div class="modal-footer">
					                <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">Save updates</button> 
					                <button class="btn btn-warning" data-dismiss="modal" aria-hidden="true">Close</button>            
					            </div>
					            
					       </div>
					       </div>
					       
					        </div>             
							</div>
							
							
                            </div>
                        </div>
                    </div>
                </div>                  
            </div>          
        </div>                  
    </div>  
</form>
<script type="text/javascript">
   function Clickheretoprint()
   { 
	   var table = $('#table').val();
	   if(table==0){
		   alert("Please Select Table First");
	   }else{
			 getValuePrint();
		     var disp_setting="toolbar=yes,location=no,directories=yes,menubar=yes,"; 
		         disp_setting+="scrollbars=yes,width=600, height=500, left=100, top=25"; 
		     var content_vlue = document.getElementById("printShow").innerHTML; 
		     
		     var docprint=window.open("","",disp_setting); 
		      docprint.document.open(); 
		      docprint.document.write('<html><head><title>Western University</title>'); 
		      docprint.document.write('</head><body onLoad="self.print()" style=" margin:0px; font-family:Verdana; font-size:10px;"><center>');          
		      docprint.document.write(content_vlue);          
		      docprint.document.write('</center></body></html>'); 
		      docprint.document.close(); 
		      docprint.focus(); 
	  }
     
   }
   function getValuePrint(){
	   
		   var table_name = $("#table option:selected").text();  
		   var date = $("#datepicker").val(); 
		   var reciept = $("#order_no").val();
		   document.getElementById('lb_table').innerHTML = table_name;
		   document.getElementById('lb_date').innerHTML = date;
		   document.getElementById('lb_reciept').innerHTML = reciept;
		   document.getElementById('lb_cashier_name').innerHTML = '<?php echo $user?>';
   }
   <?php $getfillter_add =  $this->url(array('module'=>'order','controller'=>'index','action'=>'get-order-by-id')); ?>
   
   function getOrder(id){
   	var ids =  id;
   	var cart_html1="";
   	template="";
   	subtotal=0;
   	var option = '<?php echo $this->itemsOption;?>';
   	$.ajax({
   		url:"<?php echo $getfillter_add;?>",
   		//type:"post",
   		data:{'ids':ids},
   		cache:'false',
   	    type:'POST',
   	    dataType:"json",
   		success: function(order){	
   			//order = $.parseJSON(data);
   			
   			if(order!=""){
   	   			for(var i = 1; i <= order.length; i++){
	   	   			template='<tr id="row_order_'+i+'" style="height:33px;">';
		   	   	   	template+='<td>'+i+'</td>';
		   	   	   	template+='<td><input type="hidden" value="'+order[i-1]['pro_id']+'" id="pro_id_'+i+'"/><select id="item_id_'+i+'" class="validate[required]" name="item_id_'+i+'" >'+option+'</select></td>';
		   	   	   	template+='<td><input type="hidden" value="'+order[i-1]['unit_price']+'" class="validate[required,custom[number]]" id="price'+i+'" name="price'+i+'" />'+order[i-1]['unit_price']+'</td>';
		   	   	   	template+='<td width="60px"><input type="text" class="validate[required,custom[number]] input" value="'+order[i-1]['qty']+'" id="qty'+i+'" name="qty'+i+'"/></td>';
		   	   	   	template+='<td><input type="hidden" class="input" value="'+order[i-1]['unit_price']*order[i-1]['qty']+'" readonly="readonly"  id="total'+i+'" name="total'+i+'" /></span>'+order[i-1]['unit_price']*order[i-1]['qty']+'</td>';
		   	   	   	template+='<td><span style="cursor:pointer" onclick="deleteRecord('+i+')" class="icon-trash"></span></td>';
		   	   	   	template+="</tr>";
		   	   	subtotal+=order[i-1]['unit_price']*order[i-1]['qty'];
		   	   	$('#order_item').append(template);
				$('#tables').val(order[i-1]['tab_id']).trigger('change');
		   		$('#tables').trigger('chosen:updated');
		   	 	$('#order_nos').val(order[i-1]['order_no']);
		   	 	$('#dates').val(order[i-1]['date']);
		   	//$('#item_id_'+i).chosen(); 
		   	 $('#item_id_'+i).val(order[i-1]['pro_id']);

				   	if(i!=1) {
						var id = $('#id_record').val();
						$('#id_record').val(id+','+i);
					} else {$('#id_record').val(i);}
   	   			}
	   			cart_html1='<div class="row-fluid" style="margin-top:10px">';
				cart_html1+='<div class="span8"></div>';
				cart_html1+='<div class="span4">';
					cart_html1+='<div class="total">';
						cart_html1+='<div class="span6">';
							cart_html1+='<p><strong><span>Subtotal:</span></strong></p>';
						cart_html1+='</div>';
						cart_html1+='<div class="span6">';
							cart_html1+='<p><strong>'+subtotal+' <em>USD</em></strong></p>';
						cart_html1+='</div>';
					cart_html1+='</div>';
					cart_html1+='<div class="total">';
						cart_html1+='<div class="span6">';
							cart_html1+='<p><strong><span>Subtotal:</span></strong></p>';
						cart_html1+='</div>';
						cart_html1+='<div class="span6">';
							cart_html1+='<input type="hidden" name="total" id="total" value="'+subtotal+'" /><p><strong>'+subtotal+' <em>USD</em></strong></p>';
						cart_html1+='</div>';
					cart_html1+='</div>';
				cart_html1+='</div>';
			cart_html1+='</div>';
			$('#subtotal').append(cart_html1);
   			}
   		},
   		error:function(e){
   			alert(e);
   		}
   	});
   }
   $("a[id=order_id]").on("click", function () { 
	    var a = $(this).data('index');
	    getOrder(a); 
	});
   function getItemOrder(){
		item_ids=$("#add_item").val();
		$('#add_item').val('');
		if(item_ids==-1){
			return false;
		}
		addRow(item_ids);
		$("#add_item").val("");
	}

   var ids = $('#id_record').val();
   
//    pqty = 1;num=0;
   //var index5 = '<?php //echo count($row_items);?>';
   //var option5 = '<?php //echo $this->itemsOption; ?>';
//    function addRow(item_id) {
//    	index5++;
//    	alert(index5);
//    	for(i=1; i<index5; i++){
//    		new_item=parseInt(item_id);
//    		items = parseInt($("#item_id_"+i).val());
//    		if(new_item==items){
//    			pqty=1+parseInt($("#qty"+i).val());
//    			//checkItemQuantity(new_item,pqty);
   			
//    			free = document.getElementById('free');
//    			control = document.getElementById('pricefree_'+i);
//    			if((free.checked==control.checked)){
   		
//    				newqty = parseInt($("#qty"+i).val());
//    				newqty = newqty+1;
//    				$("#qty"+i).val(newqty);
//    				$("#price"+i).val(0);
//    				 getPriceFree(i);
//    				getCurrentPrice(i);
//    				return false;
//    			}
//    			else{
//    			}
//    		}
//    	}
   	
//    	template='<tr id="row_order_'+index5+'" style="height:33px;">';
//    	num++;
   	//template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
//    	template+='<td class="quater-input" width="3%">'+num+'</td>';
//    	template+='<td class="quater-input"><select onChange="getCurrentPrice('+ index5 +');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'</select></td>';
// //    	template+='<td class="quater-input"><input type="text" onBlur="getCurrentPrice('+index5+')" value="1" class="validate[required,custom[number]] input" id="qty'+index5+'" name="qty'+index5+'" /></td>';
// //    	template+='<td class="quater-input"><input type="checkbox" Onclick="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/> <input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
// //    	template+='<td class="quater-input"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]] input" id="price'+index5+'" name="price'+index5+'"/></td>';
// //    	template+='<td class="quater-input" width="10%"><input type="text" onChange="calculatePrice('+index5+')" id="dis-value'+index5+'" name="dis-value'+index5+'" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
// //    	template+='<td class="quater-input"><input type="text" class="input" readonly="readonly" onBlur="calculatePrice('+index5+')" id="total'+index5+'" name="total'+index5+'" /></td>';
//    	template+='<td class="quater-input"><input type="text" onBlur="checkItemQuantity();getCurrentPrice('+index5+');" class="validate[required,custom[number]] input" value="1" id="qty'+index5+'" name="qty'+index5+'"/></td>';
//    	template+='<td class="quater-input"><input type="checkbox" Onclick="getPriceFree('+index5+')" id="pricefree_'+index5+'" name="pricefree_'+index5+'"/> <input type="hidden" id="oldprice_'+index5+'" name="oldprice_'+index5+'"/></td>';
//    	template+='<td class="quater-input" width="6%"><input type="text" onBlur="calculatePrice('+index5+')" class="validate[required,custom[number]] input" id="price'+index5+'" name="price'+index5+'" /></td>';
//    	template+='<td class="quater-input" width="10%"><input type="text" onChange="calculatePrice('+index5+')" id="dis-value'+index5+'" name="dis-value'+index5+'" /><input type="hidden" id="olddis_value_'+index5+'" name="olddis_value_'+index5+'"/><input type="hidden" readonly="readonly" class="input70px" id="real-value'+index5+'" name="real-value'+index5+'" /></td>';
//    	template+='<td class="quater-input"><input type="text" class="input" readonly="readonly"  id="total'+index5+'" name="total'+index5+'" /></span></td>';
//    	template+="</tr>";
   	
//    	$('#order_item').append(template);
//    	if($('#identity').val()!="") {
//    		var identity = $('#identity').val();
//    		$('#identity').val(identity+','+index5);
//    	} else {$('#identity').val(index5);}
//    	$("#pro_id_"+index5).val(item_id);
//    	$("#item_id_"+index5).val(item_id);
//    	$("#orderFrm").validationEngine();
//    	$("#pro_id_"+index5).chosen();
//    	$("#item_id_"+index5).chosen();
//    	ids=$("#pro_id_"+index5).val();
   	
//    	if(free.checked){

//    		$("#pricefree_"+index5).attr({checked:'checked'});  
//    		$("#price"+index5).val(0);
//    		$("#price"+index5).attr('readonly','readonly');
//    		$("#dis-value"+index5).attr('readonly','readonly');
//    		$("#dis-value"+index5).val(0);
//    		//$("#total"+index5).val(0);
//    	}
//    	else{
//    		$("#dis-value"+index5).val(0);
//    		$('#dis_value').val(0);
//    		$('#global_disc').val(0);
//    		getCurrentPrice(index5);
//    		//$("#discount_type"+index5).val();
//    		$("#paid").val(0);
//    	}
//    	$("#row_order_0").remove();
//    }
   	
   </script>
